deployments:
  default:
    vm_size: 4G
    port_forwarding: "8000:8000"
    environment:
      TEST_VAL=42
    ready_wait: 120
    backend_wait: 20
    auto_deploy_on_commits: true
    auto_deploy_vm_size: 1G
    subdomain_port_mapping:
      - test:81
      - test--test:81
      - another-test:8000
      - and--another-test:8000
    pre_terminate:
      - uname -a
      - ./src/scripts/script-2.sh
      - stuff-service:
        - cat ~/.bashrc
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branch:
    vm_size: 1
    environment:
      TEST_VAL=42
    ready_wait:
      120
    filename:
      ./stuff/Dockerfile
    dockerfileonly: true
    run_options: --env TEST_VAL2=${SQUASH_BRANCH_WITH_ID}
    context_path: ./stuff
    subdomains:
      Awesome Name:
        - awesomedomain,/?que=99764QQ
      Awesomness x2:
         - subd,/abc
      Awesomness x3:
         - plain
    pre_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo domain is $SQUASH_DOMAIN'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo branch id is $SQUASH_BRANCH_WITH_ID'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branchA:
    vm_size: 6
    environment:
      TEST_VAL=4242
    ready_wait:
      120
    filename:
      ./stuff/DockerfileA
    dockerfileonly: true
    run_options: --env TEST_VAL2=43 --userns=host --userns=Host
    context_path: ./stuff
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
  branchB:
    vm_size: 8GB
    environment:
      TEST_VAL=424242
    ready_wait:
      120
    filename:
      ./stuff/DockerfileB
    dockerfileonly: true
    run_options: --env TEST_VAL2=${SQUASH_DOMAIN}
    context_path: ./stuff
    post_launch:
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL2 is $TEST_VAL2'
      - target: 'stuff-service'
        command: exec
        docker: true
        options: -it {target} bash -c 'echo TEST_VAL is $TEST_VAL'
