version: '3.1'
services:
  stuff-service:
    build: ./stuff
    ports:
      - 80:80
    environment:
      - TEST_VAL
      - SQUASH_BRANCH_WITH_ID
      - SQUASH_DOMAIN
      - TEST_REPO_DEPLOYMENT
      - TEST_REPO
      - TEST_DEPLOYMENT
    volumes:
      - /:/tmp/h
      - ./shutdown.txt:/etc/shutdown.txt
      - ./test:/tmp/test.txt
